name: build pipline

on: workflow_dispatch

jobs:
  build:
    name: 'App build'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 18.x
        

    - run: npm install
    - run: chmod +x ./scripts/deploy-for-production.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: build-output
        path: ./build    # The desired behavior if no files are found using the provided path.
